Make all tests and lint pass, as it should be. Peace.
PennyDreadfulMTG/Penny-Dreadful-Tools pull request #4849
Opened 2018-05-23 15:53 UTC by bakert

2018-05-23 15:53 UTC, bakert commented
bors r+

2018-05-23 15:53 UTC, bakert commented
bors r+

2018-05-23 16:06 UTC, silasary requested changes

2018-05-23 16:06 UTC, silasary commented on decksite/templates/editmatches.mustache
> +                        {{mtgo_id}}
This is a duplicate of lines 27-32

2018-05-23 16:11 UTC, bakert commented on decksite/templates/editmatches.mustache
> +                        {{mtgo_id}}
Oh, I guess we already did this :D

2018-05-23 16:12 UTC, silasary commented on decksite/templates/editmatches.mustache
> +                        {{mtgo_id}}
The ticket was that that column didn't actually work properly 😜

2018-05-23 16:13 UTC, silasary commented
Don't revert it entirely!  The SQL addtion is still needed.

2018-05-24 03:40 UTC, silasary approved these changes

2018-05-25 07:03 UTC, silasary commented
bors r+

2018-05-25 07:11 UTC, merged