added archetype api endpoint
PennyDreadfulMTG/Penny-Dreadful-Tools pull request #9156
Opened 2021-09-23 18:33 UTC by MultiDragon

A preliminary PR to an upcoming Dreadrise release. Seems pretty straightforward, adds a `pdm/api/archetypes` endpoint which gives the list of all archetypes and their parents.

2021-09-23 23:02 UTC, bakert approved these changes

2021-09-23 23:02 UTC, bakert commented on decksite/data/archetype.py
> +        ON cl.ancestor = b.id
House style is:

    SELECT
        a.name AS name,
        b.name AS ancestor
     FROM
         …

2021-09-23 23:11 UTC, merged

2021-09-24 08:51 UTC, silasary requested changes

2021-09-24 08:51 UTC, silasary commented on decksite/controllers/api.py
> +@APP.route('/api/archetypes/')
API methods shouldn't have trailing slashes